"""initial migration

Revision ID: 362354369b5d
Revises: 896f8145aae9
Create Date: 2025-08-06 13:34:03.805590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362354369b5d'
down_revision = '896f8145aae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('STATION', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('STATION_group_id_fkey'))
        batch_op.create_foreign_key(None, 'GROUP', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'DISTRICT', ['location'], ['id'])

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'DISTRICT', ['location'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('STATION', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('STATION_group_id_fkey'), ['group_id'], unique=False)

    # ### end Alembic commands ###


